name: CI Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull nandandev/cicd-vidyut:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f cicd-vidyut-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name cicd-vidyut-container nandandev/cicd-vidyut:latest
