name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Pull Docker image
        run: sudo docker pull nandandev/cicd-vidyut:latest

      - name: Delete Old Docker container
        run: sudo docker rm -f cicd-vidyut-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name cicd-vidyut-container nandandev/cicd-vidyut:latest